"""Initial schema for SQLite

Revision ID: aef3e7be7ad0
Revises: 
Create Date: 2026-03-23 13:17:23.260185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef3e7be7ad0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('bse_code', sa.String(length=10), nullable=True),
    sa.Column('nse_symbol', sa.String(length=20), nullable=True),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap_category', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('listing_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('promoter_holding_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_active_cap', 'companies', ['is_active', 'market_cap_category'], unique=False)
    op.create_index(op.f('ix_companies_bse_code'), 'companies', ['bse_code'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_isin'), 'companies', ['isin'], unique=True)
    op.create_index(op.f('ix_companies_nse_symbol'), 'companies', ['nse_symbol'], unique=False)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index('ix_companies_sector_industry', 'companies', ['sector', 'industry'], unique=False)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_table('financials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('statement_type', sa.String(length=20), nullable=False),
    sa.Column('report_type', sa.String(length=15), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_label', sa.String(length=15), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('correction_note', sa.Text(), nullable=True),
    sa.Column('revenue_from_operations', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_of_materials', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('employee_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('finance_costs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('depreciation', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ebit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('profit_before_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_expense', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('minority_interest', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_profit_after_minority', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('eps_basic', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('eps_diluted', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('share_capital', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reserves_surplus', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('minority_interest_bs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('long_term_borrowings', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('short_term_borrowings', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fixed_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('goodwill_intangibles', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('investments', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_equivalents', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('inventory', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('receivables', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_from_operations', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_from_investing', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_from_financing', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('capex', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_change_in_cash', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('raw_source_id', sa.String(length=100), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period_label', 'statement_type', 'report_type', 'version', name='uq_financials_identity')
    )
    op.create_index('ix_fin_period_end', 'financials', ['period_end'], unique=False)
    op.create_index('ix_fin_symbol_report', 'financials', ['symbol', 'report_type', 'is_latest'], unique=False)
    op.create_index('ix_fin_symbol_type_period', 'financials', ['symbol', 'statement_type', 'period_type'], unique=False)
    op.create_index(op.f('ix_financials_symbol'), 'financials', ['symbol'], unique=False)
    op.create_table('prices',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('exchange', sa.String(length=5), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('turnover_crores', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('delivery_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=22, scale=2), nullable=True),
    sa.Column('is_split_adjusted', sa.Boolean(), nullable=True),
    sa.Column('is_bonus_adjusted', sa.Boolean(), nullable=True),
    sa.Column('dividend_amount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('data_source', sa.String(length=30), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'trade_date')
    )
    op.create_index('ix_prices_date_range', 'prices', ['trade_date'], unique=False)
    op.create_index('ix_prices_symbol_close', 'prices', ['symbol', 'close_price'], unique=False)
    op.create_index('ix_prices_symbol_date', 'prices', ['symbol', 'trade_date'], unique=False)
    op.create_table('ratios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('period_label', sa.String(length=15), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('report_type', sa.String(length=15), nullable=False),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roce', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_profit_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ebitda_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ev_to_ebitda', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ev_to_sales', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_to_sales', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_to_fcf', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('book_value_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_assets', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('interest_coverage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_debt_to_ebitda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cash_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('asset_turnover', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('inventory_turnover', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('receivables_turnover', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('capital_efficiency', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cfo_to_net_profit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fcf_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cfo_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_growth_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ebitda_growth_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_growth_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('revenue_cagr_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('revenue_cagr_5y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_cagr_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_cagr_5y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_cagr_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_cagr_5y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('eps_ttm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dividend_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('payout_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('is_ttm', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period_label', 'period_type', 'report_type', name='uq_ratios_identity')
    )
    op.create_index('ix_ratios_screen_de', 'ratios', ['debt_to_equity'], unique=False)
    op.create_index('ix_ratios_screen_npm', 'ratios', ['net_profit_margin'], unique=False)
    op.create_index('ix_ratios_screen_pe', 'ratios', ['pe_ratio'], unique=False)
    op.create_index('ix_ratios_screen_roce', 'ratios', ['roce'], unique=False)
    op.create_index('ix_ratios_screen_roe', 'ratios', ['roe'], unique=False)
    op.create_index(op.f('ix_ratios_symbol'), 'ratios', ['symbol'], unique=False)
    op.create_index('ix_ratios_symbol_period', 'ratios', ['symbol', 'period_type', 'period_label'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('saved_screens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_filters', sa.JSON(), nullable=False),
    sa.Column('display_columns', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('screen_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('triggered', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['screen_id'], ['saved_screens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('watchlists')
    op.drop_table('saved_screens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_ratios_symbol_period', table_name='ratios')
    op.drop_index(op.f('ix_ratios_symbol'), table_name='ratios')
    op.drop_index('ix_ratios_screen_roe', table_name='ratios')
    op.drop_index('ix_ratios_screen_roce', table_name='ratios')
    op.drop_index('ix_ratios_screen_pe', table_name='ratios')
    op.drop_index('ix_ratios_screen_npm', table_name='ratios')
    op.drop_index('ix_ratios_screen_de', table_name='ratios')
    op.drop_table('ratios')
    op.drop_index('ix_prices_symbol_date', table_name='prices')
    op.drop_index('ix_prices_symbol_close', table_name='prices')
    op.drop_index('ix_prices_date_range', table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_financials_symbol'), table_name='financials')
    op.drop_index('ix_fin_symbol_type_period', table_name='financials')
    op.drop_index('ix_fin_symbol_report', table_name='financials')
    op.drop_index('ix_fin_period_end', table_name='financials')
    op.drop_table('financials')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index('ix_companies_sector_industry', table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_nse_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_isin'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_bse_code'), table_name='companies')
    op.drop_index('ix_companies_active_cap', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
